# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('labeling_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'exécution")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.Lot')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('labeling_qtt', models.PositiveSmallIntegerField(verbose_name='Nombre de vignette collées')),
                ('souches_qtt', models.PositiveSmallIntegerField(verbose_name='Nombre de souches collés')),
                ('unlabeling_qtt', models.PositiveSmallIntegerField(verbose_name='Nombre de vignette enlevées')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.Employee', verbose_name='vignetteur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.Labeling')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
