# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_auto_20170717_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingdetailstempo',
            name='parent_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
