# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0006_auto_20170725_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeling',
            options={'permissions': (('can_add_labeling', 'Ajouter des bons de vignettage'), ('can_view_history', "Ajouter voir l'historique"), ('can_view_statistics', 'Ajouter voir les statistiques')), 'verbose_name': 'Rapport de vignettage'},
        ),
    ]
